id: I9DF09DD3
initial_creation_type: ebook
source_metadata:
  id: MIN-TC-16-2
  title: ༄༅།  །མཆོག་དམན་བར་མའི་ཚོགས་ལ་ཕྲིན་ཡིག་ལྷུག་པ་ཅི་བདེར་བྱས་པ་གློག་གི་རོལ་རྩེད་ཅེས་བྱ་བ་བཞུགས་སོ།
    །
  author: མཛད་པ་པོ། སྨིན་གླིང་གཏེར་ཆེན་འགྱུར་མེད་རྡོ་རྗེ།
  authors: &id001
  - མཛད་པ་པོ། སྨིན་གླིང་གཏེར་ཆེན་འགྱུར་མེད་རྡོ་རྗེ།
  sku: MIN-TC-16-2
  cover: MIN-TC-16-2.jpg
  volume: {}
ebook_metadata:
  title: ༄༅།  །མཆོག་དམན་བར་མའི་ཚོགས་ལ་ཕྲིན་ཡིག་ལྷུག་པ་ཅི་བདེར་བྱས་པ་གློག་གི་རོལ་རྩེད་ཅེས་བྱ་བ་བཞུགས་སོ།
    །
  authors: *id001
  sku: MIN-TC-16-2
  cover: MIN-TC-16-2.jpg
layers:
- Author
- BookTitle
- Chapter
- Commentary
- Yigchung
